"""update user model with new fields

Revision ID: bda773384ea5
Revises: 1908c0328f46
Create Date: 2025-08-02 02:14:28.048431+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bda773384ea5'
down_revision = '1908c0328f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
